Added pagination functionality and changed tests accordingly
ProductDock/rbc-library pull request #15
Opened 2022-03-29 09:35 UTC by vukomanv-pd

2022-03-29 12:40 UTC, NenadBecanovicPD approved these changes

2022-03-29 12:50 UTC, milicazivkov85 requested changes

2022-03-29 12:50 UTC, milicazivkov85 commented on src/main/java/com/productdock/book/BookApi.java
> +    public List<BookDto> getAll(@RequestParam int pageNumber) {
Rename method because "all" implies we will fetch all books.
`getBooks` maybe?

Also, I believe we don't need `number` embedded in `pageNumber` name because it is obvious in this context it is going to be a number.

2022-03-29 12:50 UTC, milicazivkov85 commented on src/main/java/com/productdock/book/BookService.java
> +        Pageable firstPage = PageRequest.of(pageNumber, 18);
Rename `firstPage` into `page`? It's also a good idea to have 18 as a constant here, because it kinda is important part of the logic, so it deserves its own constant. Like PAGE_SIZE?

By the way, Java 10 introduces `var`. I know we didn't use it so far, but it might be a good point to start. 
`var ... = PageRequest.of(..)`

2022-03-29 12:50 UTC, milicazivkov85 commented on src/test/java/com/productdock/book/BookApiTest.java
> +        mockMvc.perform(get("/api/books").param("pageNumber", "0"))
Integration test could be stronger. Try writing a case where you are fetching second page, instead of first one?

2022-03-29 12:50 UTC, milicazivkov85 commented on src/test/java/com/productdock/book/BookServiceShould.java
> +
remove empty line here, Given section should be grouped.
You can even remove comments, we had it just for start until we get use to given/when/then scenario, but we can get rid of them now.

2022-03-30 11:39 UTC, milicazivkov85 approved these changes

2022-03-30 11:40 UTC, merged